name: Build Go

on:
  push:
    branches: [feat/go]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
        id: go

      - name: Go version
        run: go version

      - name: Build
        run: go build -v ./...
