name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to your first issue! Thank you for taking the time to report this. I will review your issue as soon as possible. Good luck and happy coding!"
          pr-message: "Hello there! Thank you for your interest in our project. We value your contributions and are excited to have you on board. If you have any questions or need assistance, don't hesitate to ask. Happy coding!"
